// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Image from 'next/image'
import {FiPhone,FiLock,FiDownload} from 'react-icons/fi'
import Head from 'next/head'
import Link from "next/link"

export default function Home() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <>
    <Head>
      <title>FazzPay</title>
    </Head>
      <header>
        <nav>
          <div>
            <span className="logoZwallet">FazzPay</span>
          </div>
          <div className="navBtn">
            <Link href='/login'>
              <button className="buttonLogin">Login</button>
            </Link>
            <Link href='/sign-up'>
              <button className="buttonSignUp">Sign Up</button>
            </Link>
          </div>
          <div className="btnDesk">
            <Link href='/login'>
              <button className="buttonLogin">Login</button>
            </Link>
            <Link href='/sign-up'>
              <button className="buttonSignUp">Sign Up</button>
            </Link>
                
          </div>
        </nav>
        <section className="newHero">
          <div className="newHeroContent">
            <p className="titleHero colorSecondary">Awesome App For Saving <span className='colorPrimary'>Time.</span></p>
            <p className="paragHero colorSecondary">We bring you a mobile app for banking problems that <br/> oftenly wasting much of your times.</p>
            <Link href='/sign-up'>
              <button className="buttonTry">Try It Free</button>
            </Link>
          </div>
          <div className='phoneHeroImageWrap'>
            <Image src='/images/png-phone.svg' alt='img phone' height={846} width={439} />
          </div>
        </section>
      </header>


      <section className="about">
        <div className="contentabout">
          <p className="pAbout1 colorSecondary"><span className='colorPrimary'>About</span> the Application.</p>
          <p className="pAbout2 colorSecondary">We have some great features from the application and it&apos;s totally free to use by all users around the world.</p>
          <div className="blockfeature">
            <div className="block1">
              <div className="content">
                <div className='dotWrap'>
                  <FiPhone size={29} className='colorPrimary'/>
                </div>
                <p className="pblock1 colorSecondary">24/7 Support</p>
                <p className="pblock2 colorSecondaryTrans">We have 24/7 contact support so you can contact us whenever you want and we will respond it.</p>
              </div>
            </div>
            <div className="block1">
              <div className="content">
                <div className='dotWrap'>
                  <FiLock size={29} className='colorPrimary'/>
                </div>
                <p className="pblock1 colorSecondary">Data Privacy</p>
                <p className="pblock2 colorSecondaryTrans">We make sure your data is safe in our database and we will encrypt any data you submitted to us.</p>
              </div>
            </div>
            <div className="block1">
              <div className="content">
                <div className='dotWrap'>
                  <FiDownload size={29} className='colorPrimary'/>
                </div>
                <p className="pblock1 colorSecondary">Easy Download</p>
                <p className="pblock2 colorSecondaryTrans">FazzPay is 100% totally free to use it&apos;s now available on Google Play Store and App Store.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="partner">
        <div className="content">
          <div className="text">
            <p className="pText1 colorSecondary">100+ <span className='colorPrimary'>Trusted</span> <br/> Partners.</p>
            <p className="pText2 colorSecondaryTrans">We have reached global level and have 100+ <br/> brand partners around the globe.</p>
          </div>
          <Image src='/images/partner.svg' alt='phone for partner' height={270} width={560} />
        </div>
      </section>

      <section className="greatFeature">
        <div className="content">
          <Image src='/images/png-phone.svg' alt='img phone' height={846} width={439} />
          <div className="greatFeatureList">
            <p className='colorSecondary'>All The <span className='colorPrimary'>Great</span> FazzPay Features.</p>
            <div className="list">
              <p className="p1 colorSecondary"><span className='colorPrimary'>1.</span> Small Fee</p>
              <p className="p2 colorSecondaryTrans">We only charge 5% of every success transaction done in FazzPay app.</p>
            </div>
            <div className="list">
              <p className="p1 colorSecondary"><span className='colorPrimary'>2.</span> Data Secured</p>
              <p className="p2 colorSecondaryTrans">All your data is secured properly in our system and it&apos;s encrypted.</p>
            </div>
            <div className="list">
              <p className="p1 colorSecondary"><span className='colorPrimary'>3.</span> User Friendly</p>
              <p className="p2 colorSecondaryTrans">FazzPay come up with modern and sleek design and not complicated.</p>
            </div>
          </div>
        </div>
      </section>

      <section className="userSaying">
        <div className="contentabout">
          <p className="pAbout1 colorSecondary">What Users are <span className='colorPrimary'>Saying.</span></p>
          <p className="pAbout2 colorSecondary">We have some great features from the application and it&apos;s totally free to use by all users around the world.</p>
          <div className="blockSaying">
            <div className="block1">
              <div className="content">
                <Image className='responsiveImg' src='/images/1.png' alt="profile pic" width={60} height={60} />
                <p className="pblock1 colorSecondary">Sherina Chaw</p>
                <p className="pblock2 colorSecondaryTrans">“I use this app since 2 years ago and this is the best app that I&apos;ve ever use in my entire life”</p>
              </div>
            </div>
            <div className="block1">
              <div className="content">
                <Image className='responsiveImg' src='/images/2.png' alt="profile pic" width={60} height={60} />
                <p className="pblock1 colorSecondary">Jessica Mera</p>
                <p className="pblock2 colorSecondaryTrans">“I use FazzPay to manage all financial needs. It&apos;s super easy to use and it&apos;s 100% free app”</p>
              </div>
            </div>
            <div className="block1">
              <div className="content">
                <Image className='responsiveImg' src='/images/3.png' alt="profile pic" width={60} height={60} />
                <p className="pblock1 colorSecondary">Robert Chandler</p>
                <p className="pblock2 colorSecondaryTrans">“Since I&apos;m using this app, I&apos;m not going to move to another similar app. Thank you FazzPay!”</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <footer className='colorWhite'>
        <div className="content">
          <p className="pFooter1">FazzPay</p>
          <p className="pFooter2">Simplify financial needs and saving much time in banking needs with one single app.</p>
          <hr className="garis"/>
          <div className="contact">
            <p>2020 FazzPay. All right reserved.</p>
            <div className="contact2">
              <p>+62 5637 8882 9901</p>
              <p>contact@FazzPay.com</p>
            </div>
          </div>
        </div>
      </footer>
    </>
  )
}
